@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FilterCommand" as FilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

LogicManager -> FilterCommand : execute(model)
activate FilterCommand

FilterCommand -> Model : updateFilteredPersonsList(predicate)
activate Model
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : result
deactivate FilterCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommand -[hidden]->
destroy FilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
