@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title 2-Stack solution to `HistoryManager`

package undoStack {
    class State1 as "__v0:T__"
    class State2 as "__v1:T__"
    class State3 as "__v2:T__"
    class State4 as "__v7:T__"
}

State1 -[hidden]up-> State2
State2 -[hidden]up-> State3
State3 .up. State4
note right on link: new State __v7__ was added.


package redoStack {

}
note bottom of redoStack: Previous states __v4__, __v5__ and __v6__ were purged as redoStack was cleared

@end