@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class InputParser

Interface Logic <<Interface>>
Class LogicManager
    package Command {
    Class XYZCommand
    Class CommandResult
    Class "{abstract}\nCommand" as Command
    Interface UiConsumer<<Interface>>
    }
}


package UI {
Class MainWindow
}

package Model{
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .left.|> Logic
LogicManager -right->"1" InputParser
InputParser ..> XYZCommand : creates >

XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
CommandResult -left->"1" UiConsumer
UiConsumer .down.> MainWindow : consumes >
Command .up.> CommandResult : produces >
@enduml
