@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class CommandInputHistory
Class UserPrefs
Class ReadOnlyUserPrefs
Class VersionedAddressBook

Package Person {
Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Remark
Class Uuid
}

Package Tag {
Class Tag
Class CompletionStatusTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Class HiddenOutside1 #FFFFFF
HiddenOutside1 ..> ReadOnlyAddressBook



ModelManager .up.|> Model
Model .right.> ReadOnlyAddressBook
ModelManager *-down-> "1" VersionedAddressBook
ModelManager *-right-> "1" CommandInputHistory
'ModelManager *-right-> "1" CommandInputHistory
ModelManager -left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
'
AddressBook .up.|> ReadOnlyAddressBook
VersionedAddressBook -right-|> AddressBook
'

'
AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> CompletionStatusTag
Person "1" -- "*" Tag
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
Person *--> "1" Uuid
Person *--> "1" Remark

'
'Name -[hidden]right-> Phone
'Phone -[hidden]right-> Address
'Address -[hidden]right-> Email
'
'ModelManager -down->"~* filtered" Person

@enduml
